strongMan/apps/certificates/urls.py
from django.urls import re_path

from . import views

app_name = 'certificates'
urlpatterns = [
    re_path(r'add$', views.add, name='add'),
    re_path(r'add_form$', views.add_form, name='add_form'),
    re_path(r'^(?P<certificate_id>[0-9]+)$', views.details, name='details'),
    re_path(r'overview_ca$', views.overview_ca, name='overview_ca'),
    re_path(r'overview_cert$', views.overview_certs, name='overview_certs'),
    re_path(r'overview_vici$', views.overview_vici, name='overview_vici'),
    re_path(r'$', views.overview, name='overview'),
]

strongMan/urls.py
from django.conf import settings
from django.urls import re_path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .apps import views
from .apps.certificates import urls as certificates_url
from .apps.eap_secrets import urls as eap_secrets_url
from .apps.connections import urls as connections_urls
from .apps.server_connections import urls as server_connections_urls
from .apps.pools import urls as pools
from .apps.views import index

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^connections/', include(connections_urls)),
    re_path(r'^server_connections/', include(server_connections_urls)),
    re_path(r'^pools/', include(pools)),
    re_path(r'^certificates/', include(certificates_url)),
    re_path(r'^eap_secrets/', include(eap_secrets_url)),
    re_path(r'^login/?$', views.login, name='login'),
    re_path(r'^logout/?$', views.logout, name='logout'),
    re_path(r'change_pw$', views.pw_change, name='pw_change'),
    re_path(r'^about/?$', views.about, name='about'),
]

handler400 = 'strongMan.apps.views.bad_request'
handler403 = 'strongMan.apps.views.permission_denied'
handler404 = 'strongMan.apps.views.page_not_found'
handler500 = 'strongMan.apps.views.server_error'

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

strongMan/apps/certificates/forms.py
from django import forms

from .container_reader import ContainerDetector, ContainerTypes


class CertificateSearchForm(forms.Form):
    search_text = forms.CharField(max_length=200, required=False)


class AddForm(forms.Form):
    cert = forms.FileField(label="Certificate container", required=True)
    password = forms.CharField(label="Password", max_length=60, required=False)
    cert_bytes = None

    def is_valid(self):
        valid = super(AddForm, self).is_valid()
        if not valid:
            return False
        return self.container_type() != ContainerTypes.Undefined

    def container_type(self):
        '''
        Detects the type of the uploaded Container
        :return: ContainerTypes
        '''
        password = self._read_password()
        cert_bytes = self._cert_bytes()
        detected_type = ContainerDetector.detect_type(cert_bytes, password=password)
        return detected_type

    def _cert_bytes(self):
        if self.cert_bytes is None:
            self.cert_bytes = self.cleaned_data['cert'].read()
        return self.cert_bytes

    def _read_password(self):
        password = self.cleaned_data["password"]
        if password == "":
            return None
        password_bytes = str.encode(password)
        return password_bytes


class ChangeNicknameForm(forms.Form):
    nickname = forms.CharField(max_length=100, required=True)

strongMan/apps/certificates/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_http_methods

from strongMan.apps.certificates.models.certificates import Certificate
from strongMan.apps.certificates.request_handler import OverviewHandler
from strongMan.apps.certificates.request_handler.DetailsHandler import DetailsHandler
from .forms import AddForm
from .request_handler.AddHandler import AddHandler
from .tables import UserCertificateTable
from .models import UserCertificate
from django_tables2 import RequestConfig


@login_required
@require_http_methods(["GET", "POST"])
def overview(request):
    handler = OverviewHandler.MainOverviewHandler.by_request(request)
    return handler.handle()


@login_required
@require_http_methods(["GET", "POST"])
def overview_ca(request):
    handler = OverviewHandler.RootOverviewHandler.by_request(request)
    return handler.handle()


@login_required
@require_http_methods(["GET", "POST"])
def overview_certs(request):
    handler = OverviewHandler.EntityOverviewHandler.by_request(request)
    return handler.handle()


@login_required
@require_http_methods(["GET", "POST"])
def overview_vici(request):
    handler = OverviewHandler.ViciOverviewHandler.by_request(request)
    return handler.handle()


@login_required
@require_http_methods(["GET", "POST"])
def add(request):
    if request.method == 'POST':
        handler = AddHandler.by_request(request)
        (request, html, context) = handler.handle()
        return render(request, html, context)
    elif request.method == 'GET':
        form = AddForm()
        return render(request, 'certificates/add.html', {"form": form})


@login_required
@require_http_methods(["GET", "POST"])
def details(request, certificate_id):
    certificate = get_object_or_404(Certificate, id=certificate_id)
    handler = DetailsHandler(request, certificate)
    return handler.handle()

strongMan/apps/certificates/views/AddHandler.py
from django.contrib import messages
from oscrypto.errors import AsymmetricKeyError

from strongMan.apps.certificates.forms import AddForm
from ..services import UserCertificateManager


class AddHandler(object):
    def __init__(self, is_add_form=False):
        self.form = None
        self.request = None
        self.is_add_form = is_add_form

    @classmethod
    def by_request(cls, request, is_add_form=False):
        handler = cls(is_add_form)
        handler.request = request
        return handler

    def _render_upload_page(self, form=AddForm()):
        if self.is_add_form:
            return self.request, 'certificates/add_form.html', {"form": form}
        else:
            return self.request, 'certificates/add.html', {"form": form}

    def _render_added_page(self, result):
        context = {"private": result.privatekey, "public": result.certificate,
                   "further_publics": result.further_certificates}
        if self.is_add_form:
            return self.request, 'certificates/added_form.html', context
        else:
            return self.request, 'certificates/added.html', context

    def handle(self):
        '''
        Handles a Add Container request. Adds the specific container to the database
        :return: a rendered site specific for the request
        '''
        self.form = AddForm(self.request.POST, self.request.FILES)
        if not self.form.is_valid():
            messages.add_message(self.request, messages.ERROR,
                                 'No valid container detected. Maybe your container needs a password?')
            return self._render_upload_page(form=self.form)

        try:
            result = UserCertificateManager.add_keycontainer(self.form._cert_bytes(),
                                                             self.form._read_password())
            for e in result.exceptions:
                messages.add_message(self.request, messages.WARNING, str(e))
            if not result.success:
                return self._render_upload_page()

            if result.certificate is not None and result.privatekey is None:
                result.privatekey = result.certificate.private_key
            if result.certificate is None and result.privatekey is not None:
                result.certificate = result.privatekey.certificates.all()[0]

            return self._render_added_page(result)

        except (ValueError, TypeError, AsymmetricKeyError, OSError):
            messages.add_message(self.request, messages.ERROR,
                                 "Error reading file. Maybe your file is corrupt?")
            return self._render_upload_page(form=self.form)
        except Exception as e:
            messages.add_message(self.request, messages.ERROR,
                                 "Internal error: " + str(e))
            return self._render_upload_page(form=self.form)

strongMan/apps/certificates/views/DetailsHandler.py
import oscrypto.asymmetric
from urllib.parse import quote

from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from ..models import UserCertificate, ViciCertificate, CertificateDoNotDelete
from ..forms import ChangeNicknameForm


class DetailsHandler(object):
    def __init__(self, request, certificate_object):
        self.request = request
        self.certificate = certificate_object
        self._usercert = self._certificate_subclass(classe=UserCertificate)
        self._vicicert = self._certificate_subclass(classe=ViciCertificate)

    def _render_vici_details(self):
        return render(self.request, 'certificates/details.html',
                      {"certificate": self._vicicert, "readonly": True})

    def _render_user_details(self):
        if self._usercert.private_key is None:
            return render(self.request, 'certificates/details.html',
                          {"certificate": self._usercert, "readonly": False})
        else:
            return render(self.request, 'certificates/details.html',
                          {"certificate": self._usercert, 'private': self._usercert.private_key,
                           "readonly": False})

    def handle(self):
        if self._is_vicicert():
            if self.request.method == "POST" and "export_cert" in self.request.POST:
                return self._export_certificate()
            return self._render_vici_details()

        if self.request.method == "GET":
            return self._render_user_details()
        elif self.request.method == "POST":
            if "export_cert" in self.request.POST:
                return self._export_certificate()
            if "remove_cert" in self.request.POST:
                return self._delete_cert()
            elif "remove_privatekey" in self.request.POST:
                return self._delete_private_key()
            elif "update_nickname" in self.request.POST:
                if not self._is_usercert():
                    return self._render_user_details()
                form = ChangeNicknameForm(self.request.POST)
                if form.is_valid():
                    self._usercert.nickname = form.cleaned_data["nickname"]
                    self._usercert.save()
                    return self._render_user_details()
        return self._render_user_details()

    def _certificate_subclass(self, classe):
        try:
            return classe.objects.get(id=self.certificate.id)
        except Exception:
            return None

    def _is_vicicert(self):
        return self._vicicert is not None

    def _is_usercert(self):
        return self._usercert is not None

    def _delete_cert(self):
        cname = self.certificate.subject.cname
        try:
            self.certificate.delete()
            messages.add_message(self.request, messages.INFO, "Certificate '" + cname + "' has been "
                                 "removed.")
            return HttpResponseRedirect(reverse('certificates:overview'))
        except CertificateDoNotDelete as e:
            messages.add_message(self.request, messages.ERROR, "Can't delete certificate. " + str(e))
            return self._render_user_details()

    def _delete_private_key(self):
        try:
            self._usercert.remove_privatekey()
            messages.add_message(self.request, messages.INFO, "Private key has been removed.")
        except CertificateDoNotDelete as e:
            messages.add_message(self.request, messages.ERROR, "Can't delete private key. " + str(e))

        return self._render_user_details()

    def _export_certificate(self):
        try:
            cert = oscrypto.asymmetric.load_certificate(self.certificate.der_container)
            pem_bytes = oscrypto.asymmetric.dump_certificate(cert)

            filename = quote(self._vicicert.nickname if self._is_vicicert() else self._usercert.nickname)

            response = HttpResponse(pem_bytes, content_type="application/x-pem-file")
            response['Content-Disposition'] = "attachment; filename*=utf-8''%s.pem" % filename
            return response
        except Exception as e:
            messages.add_message(self.request, messages.ERROR, "Couldn't export the cert. " + str(e))
            return self._render_user_details()

strongMan/apps/certificates/views/OverviewHandler.py
from django.contrib import messages
from django.shortcuts import render
from django_tables2 import RequestConfig

from strongMan.helper_apps.vici.wrapper.exception import ViciSocketException
from .. import models
from ..forms import CertificateSearchForm
from ..models import UserCertificate
from ..services import ViciCertificateManager
from ..tables import UserCertificateTable


class AbstractOverviewHandler(object):
    def __init__(self):
        self.request = None
        self.ENTRIES_PER_PAGE = 10

    @classmethod
    def by_request(cls, request):
        handler = cls()
        handler.request = request
        return handler

    def page_tag(self):
        '''
        A string that identifies the view. This gets populated to the template.
        :return:
        '''
        raise NotImplementedError()

    def all_certificates(self):
        '''
        Returns all possible certificates. Can raise a OvervieHandlerException
        '''
        raise NotImplementedError()

    def _search_for(self, all_certs, search_text):
        '''
        Searches for keywords in certificates
        :param all_certs: prefiltered list of certificates
        :param search_text: text to search for
        :return: queryset of filtered certificates
        '''
        cert_ids = []
        cert_ids += self._search_for_indentities(search_text)
        cert_ids += self._search_for_nicknames(all_certs, search_text)
        return all_certs.filter(pk__in=cert_ids)

    def _search_for_indentities(self, search_text):
        '''
        Searches for keywords in identities
        :param search_text: text to search for
        :return: list of certificate id's
        '''
        cert_ids = []
        identities = models.identities.AbstractIdentity.objects.all()
        identities = models.identities.AbstractIdentity.subclasses(identities)
        for ident in identities:
            if search_text.lower() in str(ident).lower():
                cert_ids.append(ident.certificate.pk)
        return cert_ids

    def _search_for_nicknames(self, all_certs, search_text):
        '''
        Searches for keywords in nicknames
        :param all_certs: list of prefiltered certificates
        :param search_text: text to search for
        :return: list of certificate id's
        '''
        cert_ids = []

        for cert in all_certs:
            if search_text.lower() in cert.nickname.lower():
                cert_ids.append(cert.pk)
        return cert_ids

    def _render(self, queryset=UserCertificate.objects.none(), search_pattern=""):
        table = UserCertificateTable(queryset, request=self.request)
        RequestConfig(self.request, paginate={"per_page": self.ENTRIES_PER_PAGE}).configure(table)
        if len(queryset) == 0:
            table = None
        return render(self.request, 'certificates/overview.html',
                      {'table': table, "view": self.page_tag(), "search_pattern": search_pattern})

    def handle(self):
        try:
            all_certs = self.all_certificates()
        except OverviewHandlerException as e:
            messages.add_message(self.request, messages.WARNING, str(e))
            return self._render()

        if self.request.method == "GET":
            return self._render(all_certs)

        form = CertificateSearchForm(self.request.POST)
        if not form.is_valid():
            return self._render(all_certs)

        search_pattern = form.cleaned_data["search_text"]
        if not search_pattern == '':
            search_result = self._search_for(all_certs, search_pattern)
        else:
            search_result = all_certs
        return self._render(search_result, search_pattern)


class ViciOverviewHandler(AbstractOverviewHandler):
    def page_tag(self):
        return "vici"

    def all_certificates(self):
        try:
            ViciCertificateManager.reload_certs()
        except ViciSocketException:
            return []
        return models.certificates.ViciCertificate.objects.all()


class EntityOverviewHandler(AbstractOverviewHandler):
    def page_tag(self):
        return "entities"

    def all_certificates(self):
        return models.certificates.UserCertificate.objects.filter(is_CA=False)


class MainOverviewHandler(AbstractOverviewHandler):
    def page_tag(self):
        return "all"

    def all_certificates(self):
        return models.certificates.UserCertificate.objects.all()


class RootOverviewHandler(AbstractOverviewHandler):
    def page_tag(self):
        return "root"

    def all_certificates(self):
        return models.certificates.UserCertificate.objects.filter(is_CA=True)


class OverviewHandlerException(Exception):
    pass

strongMan/apps/certificates/templates/certificates/add.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}Certificates{% endblock title %}
{% block small-title %}Upload a key container{% endblock small-title %}
{% block html-head %}
    <script src="{% static 'certificates/fileinput.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'certificates/fileinput.min.css' %}">
    <link href="{% static 'certificates/certificates.css' %}" rel="stylesheet">

{% endblock html-head %}
{% block content %}
    {% include "certificates/widgets/AddCert.html" %}
{% endblock content %}

strongMan/apps/certificates/templates/certificates/add_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/callout.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'certificates/fileinput.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'certificates/fileinput.min.css' %}">
    <link href="{% static 'certificates/certificates.css' %}" rel="stylesheet">
</head>
<body>
{% if messages %}
    <div class="row">
        <div class="col-xs-12">
            {% for message in messages %}
                <div class="alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %} fade in">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>{{ message }}</strong>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}
{% include "certificates/widgets/AddCert.html" with is_form=True %}
</body>
</html>

strongMan/apps/certificates/templates/certificates/added.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block html-head %}
    <link href="{% static 'certificates/certificates.css' %}" rel="stylesheet">
{% endblock html-head %}
{% block title %}Certificates{% endblock title %}
{% block small-title %}You have successfully added a container{% endblock small-title %}
{% block content %}
    {% include "certificates/widgets/AddedCert.html" %}
{% endblock content %}

strongMan/apps/certificates/templates/certificates/added_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Added</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/callout.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'certificates/fileinput.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'certificates/fileinput.min.css' %}">
    <link href="{% static 'certificates/certificates.css' %}" rel="stylesheet">
</head>
<body>
    {% include "certificates/widgets/AddedCert.html" with is_form=True %}
</body>
</html>

strongMan/apps/certificates/templates/certificates/edit.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}Certificates{% endblock title %}
{% block small-title %}Details{% endblock small-title %}
{% block content %}
    {{ readonly }}
    <div class="container" id="certificate-detail">
        <div class="row">
            {% if certificate %}
                <div class="col-lg-1"></div>
                <div class="col-sm-12 col-md-6 col-lg-4 x509-edit">
                    <div class="row">
                        {% include "certificates/widgets/PublicKey_view.html" with x509=certificate %}
                    </div>
                    {% if certificate.source != "V" %}
                    <div class="row text-center">
                        <form action="" method="POST" style="display: inline;">
                            {% csrf_token %}
                            <span title="Remove certificate">
                                <button type="submit" class="btn btn-default remove-btn" name="remove_cert"
                                        id="remove_cert-btn">
                                    <span class="glyphicon glyphicon-remove"></span> Remove certificate
                                </button>
                            </span>
                        </form>
                    </div>
                    {% endif %}
                </div>
            {% endif %}
            {% if private %}
                <div class="col-md-1 col-lg-2"></div>
                <div class="col-sm-12 col-md-5 col-lg-4 private-edit">
                    <div class="row">
                        {% include "certificates/widgets/PrivateKey_view.html" with private=private %}
                    </div>
                    <div class="row text-center">
                        <form action="" method="POST" style="display: inline;">
                            {% csrf_token %}
                                <span title="Remove private key">
                                    <button type="submit" class="btn btn-default remove-btn" name="remove_privatekey"
                                            id="remove_privatekey-btn">
                                        <span class="glyphicon glyphicon-remove"></span> Remove private key
                                    </button>
                                </span>
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
        <script>
            $(".remove-btn")
                    .mouseenter(function () {
                        $("#" + this.id).removeClass('btn-default').addClass('btn-danger');
                    })
                    .mouseleave(function () {
                        $(".remove-btn").removeClass('btn-danger').addClass('btn-default');
                    });
        </script>
    </div>
{% endblock content %}

strongMan/apps/certificates/templates/certificates/overview.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load render_table from django_tables2 %}
{% comment %}
    Input:
    :param publics: list of certificates
    :type publics: [models.Certifacte]
    :param view: indicates which filter has been applied
    :type view: "all" | "root" | "entities"
    :param search_pattern: the search pattern, that the user has typed in
    :type search_pattern: String
    :param readonly: Indicates if the view is readonly
    :type readonly: boolean
{% endcomment %}
{% block title %}Certificates{% endblock title %}
{% block small-title %}Overview{% endblock small-title %}
{% block html-head %}
    <link href="{% static 'certificates/certificates.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}" />
{% endblock %} html-header %}
{% block content %}
    <div id="certificate-overview" class="row col-xs-12 col-md-10 col-md-offset-1">
        <div class="row" id="header">
            <div class="col-md-10 col-xs-9 btn-group" role="group">
                <a href="{% url "certificates:overview" %}" {% if view == "all" %}disabled="True" {% endif %}
                   class="btn btn-default" title="Show all certificates">
                        All
                </a>
                <a href="{% url 'certificates:overview_ca' %}" {% if view == "root" %}disabled="True" {% endif %}
                   class="btn btn-default" title="Show only root certificates">
                        Root
                </a>
                <a href="{% url 'certificates:overview_certs' %}" {% if view == "entities" %}disabled="True" {% endif %}
                   class="btn btn-default" title="Show only entity certificates">
                        Entities
                </a>
                <a href="{% url 'certificates:overview_vici' %}" {% if view == "vici" %}disabled="True" {% endif %}
                   class="btn btn-default" title="Shows the certificates provided by the vici interface">
                        Vici
                </a>
            </div>
            <div class="pull-right" id="add-btn">
                <span title="Add a new key container">
                    <a href="{% url "certificates:add" %}" type="button" class="btn btn-primary btn-sm"
                       aria-label="Left Align">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add
                    </a>
                </span>
            </div>
        </div>

        <div class="row" id="search">
            <form action="" method="POST" >
                {% csrf_token %}
                <input type="hidden" name="page" value="1">
                <div class="col-xs-12">
                    <div class="input-group">
                        <input class="form-control" type="text" name="search_text" value="{{ search_pattern }}"
                               placeholder="Filter your certificates by domain names">
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default" type="button" name="search" {% if not table %}disabled="True"{% endif %}><span
                                    class="glyphicon glyphicon-search"></span> Search
                            </button>
                            <a href="" class="btn btn-default" {% if search_pattern == "" %}disabled="True"{% endif %}
                               name="clear">
                                <span class="glyphicon glyphicon-remove"></span> Clear
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    {% if table %}
        <div class="col-xs-12">
        {% render_table table 'certificates/widgets/table.html' %}
        </div>
    {% else %}
        <h3 id="no_certs_to_show">No certificates to show</h3>
        <p>Feel free to add a key container with the blue Add button on the right side.</p>
    {% endif %}
    </div>
{% endblock content %}