strongMan/apps/certificates/urls.py
from django.urls import re_path

from . import views

app_name = 'certificates'
urlpatterns = [
    re_path(r'add$', views.add, name='add'),
    re_path(r'add_form$', views.add_form, name='add_form'),
    re_path(r'^(?P<certificate_id>[0-9]+)$', views.details, name='details'),
    re_path(r'overview_ca$', views.overview_ca, name='overview_ca'),
    re_path(r'overview_cert$', views.overview_certs, name='overview_certs'),
    re_path(r'overview_vici$', views.overview_vici, name='overview_vici'),
    re_path(r'$', views.overview, name='overview'),
]

strongMan/apps/connections/urls.py
from django.urls import re_path

from . import views

app_name = 'connections'
urlpatterns = [
    re_path(r'^$', views.overview, name='index'),
    re_path(r'^add/$', views.create, name='choose'),
    re_path(r'^(?P<id>\d+)/$', views.update, name='update'),
    re_path(r'delete/(?P<id>\d+)/$', views.delete_connection, name='delete'),
    re_path(r'state/(?P<id>\d+)/$', views.get_state, name='state'),
    re_path(r'log/$', views.get_log, name='log'),
    re_path(r'toggle/$', views.toggle_connection, name='toggle'),
    re_path(r'info/$', views.get_sa_info, name='info'),
    re_path(r'certificatepicker/$', views.get_certificatepicker, name='certificatepicker'),
    re_path(r'capicker/$', views.get_capicker, name='capicker'),
]

strongMan/urls.py
from django.conf import settings
from django.urls import re_path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .apps import views
from .apps.certificates import urls as certificates_url
from .apps.eap_secrets import urls as eap_secrets_url
from .apps.connections import urls as connections_urls
from .apps.server_connections import urls as server_connections_urls
from .apps.pools import urls as pools
from .apps.views import index

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^connections/', include(connections_urls)),
    re_path(r'^server_connections/', include(server_connections_urls)),
    re_path(r'^pools/', include(pools)),
    re_path(r'^certificates/', include(certificates_url)),
    re_path(r'^eap_secrets/', include(eap_secrets_url)),
    re_path(r'^login/?$', views.login, name='login'),
    re_path(r'^logout/?$', views.logout, name='logout'),
    re_path(r'change_pw$', views.pw_change, name='pw_change'),
    re_path(r'^about/?$', views.about, name='about'),
]

handler400 = 'strongMan.apps.views.bad_request'
handler403 = 'strongMan.apps.views.permission_denied'
handler404 = 'strongMan.apps.views.page_not_found'
handler500 = 'strongMan.apps.views.server_error'

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

strongMan/apps/connections/forms/FormFields.py
from django import forms
from strongMan.apps.certificates.models import UserCertificate


class CertificateChoice(forms.ModelChoiceField):
    @property
    def is_certificate_choice(self):
        return True


class IdentityChoiceValue(object):
    def __init__(self, identity):
        self.identity = identity

    def __str__(self):
        return str(self.identity)

    def type(self):
        return self.identity.type()


class IdentityChoice(forms.ChoiceField):
    def __init__(self, *args, **kwargs):
        super(IdentityChoice, self).__init__(*args, **kwargs)
        self._certificate = None

    @property
    def is_identity_choice(self):
        return True

    @property
    def certificate(self):
        return self._certificate

    @certificate.setter
    def certificate(self, value):
        self._certificate = value
        self.choices = IdentityChoice.to_choices(self._certificate.identities.all())

    @classmethod
    def load_identities(cls, form, certificate_field_name, identity_field_name):
        data_source = {}
        if not form.data == {}:
            data_source = form.data
        elif not form.initial == {}:
            data_source = form.initial
        else:
            return
        if certificate_field_name not in data_source:
            return
        cert_id = data_source[certificate_field_name]
        cert = UserCertificate.objects.filter(pk=cert_id).first()
        identity = form.fields[identity_field_name]
        if not identity.certificate == cert and cert is not None:
            identity.certificate = cert

    @classmethod
    def to_choices(cls, identity_queryset):
        choices = []
        for ident in identity_queryset:
            subident = ident.subclass()
            choice = (subident.pk, IdentityChoiceValue(subident))
            choices.append(choice)
        return choices

strongMan/apps/connections/forms/core.py
from django import forms
from strongMan.apps.certificates.models import UserCertificate


class CertificateChoice(forms.ModelChoiceField):
    @property
    def is_certificate_choice(self):
        return True


class IdentityChoiceValue:
    def __init__(self, identity):
        self.identity = identity

    def __str__(self):
        return str(self.identity)

    def type(self):
        return self.identity.type()


class IdentityChoice(forms.ChoiceField):
    def __init__(self, *args, **kwargs):
        super(IdentityChoice, self).__init__(*args, **kwargs)
        self._certificate = None

    @property
    def is_identity_choice(self):
        return True

    @property
    def certificate(self):
        return self._certificate

    @certificate.setter
    def certificate(self, value):
        self._certificate = value
        self.choices = IdentityChoice.to_choices(self._certificate.identities.all())

    @classmethod
    def load_identities(cls, form, certificate_field_name, identity_field_name):
        data_source = {}
        if not form.data == {}:
            data_source = form.data
        elif not form.initial == {}:
            data_source = form.initial
        else:
            return
        if not certificate_field_name in data_source:
            return
        cert_id = data_source[certificate_field_name]
        cert = UserCertificate.objects.filter(pk=cert_id).first()
        identity = form.fields[identity_field_name]
        if not identity.certificate == cert and cert is not None:
            identity.certificate = cert

    @classmethod
    def to_choices(cls, identity_queryset):
        choices = []
        for ident in identity_queryset:
            subident = ident.subclass()
            choice = (subident.pk, IdentityChoiceValue(subident))
            choices.append(choice)
        return choices

strongMan/apps/connections/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods


from .request_handler.CreateHandler import AddHandler
from .request_handler.UpdateHandler import UpdateHandler
from .request_handler.OverviewHandler import OverviewHandler
from .request_handler.DeleteHandler import DeleteHandler
from .request_handler.ToggleHandler import ToggleHandler
from .request_handler.StateHandler import StateHandler
from .request_handler.LogHandler import LogHandler
from .request_handler.SaInfoHandler import SaInfoHandler
from .request_handler.IdentitiesHandler import IdentitiesHandler

@require_http_methods('GET')
@login_required
def overview(request):
    handler = OverviewHandler(request)
    return handler.handle()


@login_required
@require_http_methods(['POST', 'GET'])
def create(request):
    handler = AddHandler(request)
    return handler.handle()


@login_required
def update(request, id):
    handler = UpdateHandler(request, id)
    return handler.handle()


@login_required
@require_http_methods('POST')
def toggle_connection(request):
    handler = ToggleHandler(request)
    return handler.handle()


@login_required
def delete_connection(request, id):
    handler = DeleteHandler(request, id)
    return handler.handle()


@login_required
@require_http_methods('POST')
def get_state(request, id):
    handler = StateHandler(request, id)
    return handler.handle()


@login_required
@require_http_methods('POST')
def get_log(request):
    handler = LogHandler(request)
    return handler.handle()

@login_required
@require_http_methods('POST')
def get_sa_info(request):
    handler = SaInfoHandler(request)
    return handler.handle()

@login_required
@require_http_methods('POST')
def get_identities(request):
    handler = IdentitiesHandler(request)
    return handler.handle()



def _get_title(form):
    return form.get_choice_name()


def _get_type_name(cls):
    return type(cls).__name__

strongMan/apps/connections/views/CaPickerHandler.py
from django.shortcuts import render

from ..forms.ConnectionForms import Ike2CertificateForm


class CaPickerHandler(object):
    def __init__(self, request):
        self.request = request

    def handle(self):
        form = Ike2CertificateForm()
        return render(self.request,
                      'connections/forms/CaPicker.html', {"form": form})

strongMan/apps/connections/views/CertificatePickerHandler.py
from django.shortcuts import render, get_object_or_404

from ..forms.ConnectionForms import Ike2CertificateForm
from ...certificates.models import UserCertificate


class CertificatePickerHandler(object):
    def __init__(self, request):
        self.request = request

    def _render(self, form):
        return render(self.request,
                      'connections/forms/CertificatePicker.html',
                      {"certificate": form['certificate'], "identity": form['identity']})

    def handle(self):
        cert = self._certificate_id()

        if cert is None:
            form = Ike2CertificateForm()
        else:
            form = Ike2CertificateForm(initial={'certificate': cert})

        form.update_certificates()
        return self._render(form)

    def _certificate_id(self):
        if "certififcate_id" not in self.request.POST:
            return None

        cert = self.request.POST["certififcate_id"]
        if cert == "-1" or cert == '':
            return None

        get_object_or_404(UserCertificate, pk=cert)
        return cert

strongMan/apps/connections/views/CreateHandler.py
from django.shortcuts import render, redirect
from django.urls import reverse

from ..forms.ConnectionForms import AbstractDynamicForm, ChooseTypeForm
from ..forms.SubForms import HeaderForm


class AddHandler(object):
    def __init__(self, request):
        self.request = request

    def _render(self, form=ChooseTypeForm()):
        return render(self.request, 'connections/Detail.html', {"form": form})

    def _abstract_form(self):
        '''
        Intiates and validates the Abstract form
        :return Valid abstract form
        '''
        form = AbstractDynamicForm(self.request.POST)
        if not form.is_valid():
            raise Exception("No valid form detected." + str(form.errors))
        return form

    def handle(self):
        if self.request.method == "GET":
            return self._render()
        elif self.request.method == "POST":
            abstract_form = self._abstract_form()
            form_class = abstract_form.current_form_class

            form = form_class(self.request.POST)
            form.update_certs()
            if not form.is_valid():
                return self._render(form)

            if form_class == ChooseTypeForm:
                return self._render(form=form.selected_form_class())

            if isinstance(form, HeaderForm):
                form.create_connection()
                return redirect(reverse("connections:index"))

strongMan/apps/connections/views/DeleteHandler.py
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from strongMan.helper_apps.vici.wrapper.exception import ViciException

from strongMan.apps.connections.models.connections import Connection
from strongMan.helper_apps.vici.wrapper.wrapper import ViciWrapper


class DeleteHandler(object):
    def __init__(self, request, id):
        self.request = request
        self.id = id

    def handle(self):
        connection = Connection.objects.get(id=self.id).subclass()
        try:
            vici_wrapper = ViciWrapper()
            if vici_wrapper.is_connection_loaded(connection.profile) is True:
                vici_wrapper.unload_connection(connection.profile)
        except ViciException as e:
            messages.warning(self.request, str(e))

        profilname = connection.profile
        connection.delete()
        messages.info(self.request, "Connection " + profilname + " deleted.")
        return HttpResponseRedirect(reverse("connections:index"))

strongMan/apps/connections/views/LogHandler.py
import time
from datetime import timedelta
from django.utils import timezone

from django.http import JsonResponse

from strongMan.apps.connections.models.specific import LogMessage


class LogHandler(object):
    def __init__(self, request):
        self.newest_log = None
        self.id = int(request.POST.get('id'))

    def handle(self):
        response = dict(logs=[])
        self._delete_old_logs()
        if self.id < 0:
            logs = self._get_logs()
        else:
            logs = self._get_new_logs()
        for log in logs:
            log_dict = dict(id=log.id, message=log.message, name=log.connection.profile)
            log_dict['timestamp'] = log.timestamp.strftime("%Y-%m-%d %H:%M:%S")
            response['logs'].append(log_dict)
        return JsonResponse(response)

    def _delete_old_logs(self):
        time_threshold = timezone.now() - timedelta(minutes=5)
        LogMessage.objects.filter(timestamp__lt=time_threshold).delete()

    def _get_logs(self):
        while LogMessage.objects.all().count() == 0:
            time.sleep(1)
        return LogMessage.objects.all().order_by('timestamp')

    def _get_new_logs(self):
        logs = LogMessage.objects.filter(pk__gt=self.id).order_by('timestamp')
        while logs.count() == 0:
            time.sleep(1)
            logs = LogMessage.objects.filter(pk__gt=self.id).order_by('timestamp')
        return logs

strongMan/apps/connections/views/OverviewHandler.py
from django.contrib import messages
from django.shortcuts import render
from django_tables2 import RequestConfig

from strongMan.apps.connections.models.connections import Connection
from strongMan.helper_apps.vici.wrapper.exception import ViciException
from ..tables import ConnectionTable


class OverviewHandler(object):
    def __init__(self, request):
        self.request = request
        self.ENTRIES_PER_PAGE = 10

    def handle(self):
        try:
            return self._render()
        except ViciException as e:
            messages.warning(self.request, str(e))

    def _render(self):
        queryset = Connection.objects.all()
        table = ConnectionTable(queryset, request=self.request)
        RequestConfig(self.request, paginate={"per_page": self.ENTRIES_PER_PAGE}).configure(table)
        if len(queryset) == 0:
            table = None
        return render(self.request, 'connections/overview.html', {'table': table})

strongMan/apps/connections/views/SaInfoHandler.py
from django.http import JsonResponse
from strongMan.helper_apps.vici.wrapper.exception import ViciException

from strongMan.apps.connections.models.connections import Connection
from strongMan.helper_apps.vici.wrapper.wrapper import ViciWrapper


class SaInfoHandler(object):
    def __init__(self, request):
        self.request = request
        self.id = int(request.POST.get('id'))

    @property
    def connection(self):
        return Connection.objects.get(pk=self.id).subclass()

    def handle(self):
        response = dict(id=self.connection.id, success=False)
        try:
            vici_wrapper = ViciWrapper()
            sa = vici_wrapper.get_sas_by(self.connection.profile)
            if sa:
                child = ChildSA(sa[0], self.connection.profile)
                response['child'] = child.__dict__
                response['success'] = True
        except ViciException as e:
            response['message'] = str(e)
        except Exception as e:
            print(e)

        return JsonResponse(response)


class ChildSA(object):
    def __init__(self, sa, connection_name):
        sa = sa[connection_name]
        child_sas = sa['child-sas']
        child_sa = child_sas[connection_name]
        self.remote_ts = child_sa['remote-ts'][0].decode('ascii')
        self.local_ts = child_sa['local-ts'][0].decode('ascii')
        self.bytes_in = child_sa['bytes-in'].decode('ascii')
        self.bytes_out = child_sa['bytes-out'].decode('ascii')
        self.packets_in = child_sa['packets-in'].decode('ascii')
        self.packets_out = child_sa['packets-out'].decode('ascii')

strongMan/apps/connections/views/StateHandler.py
from django.http import JsonResponse

from strongMan.apps.connections.models.connections import Connection


class StateHandler(object):
    def __init__(self, request, id):
        self.request = request
        self.id = id

    @property
    def connection(self):
        return Connection.objects.get(pk=self.id).subclass()

    def handle(self):
        response = dict(id=self.connection.id, success=True)
        response['state'] = self.connection.state
        return JsonResponse(response)

strongMan/apps/connections/templates/connections/forms/CaPicker.html
{% with certificate=form.certificate_ca identity=form.identity_ca is_server_identity=form.is_server_identity certificate_ca_auto=form.certificate_ca_auto ca_exists=form.ca_certificate_exists %}
    <div id="ca_picker_{{ certificate.name }}">
        <div class="row certificate_ca_auto">
            <label class="control-label col-sm-3 col-xs-12">CA/Server certificate</label>
            <div class="col-sm-8 col-xs-10">
        <span {% if ca_exists == False %}title="Choose automatically has been disabled because strongMan doesn't contains any certificate." {% endif %}>
        <input type="checkbox" class="certificate_ca_auto" name="{{ certificate_ca_auto.name }}"
               id="{{ certificate_ca_auto.name }}"
               {% if certificate_ca_auto.value and ca_exists %}checked{% endif %}
               {% if ca_exists == False %}disabled{% endif %}>
        Choose automatically</span>
            </div>
        </div>
        <div class="row ca_picker">
            <label class="control-label col-sm-3"></label>
            <div class="col-sm-8 col-xs-10">
                <select class="selectpicker" data-live-search="true"
                        name="{{ certificate.name }}"
                        id="id_{{ certificate.name }}" data-show-subtext="True">
                    {% if certificate.value == None or certificate.value == '-1' %}
                        <option value="-1" selected>Nothing selected</option>
                    {% endif %}
                    {% for choise in certificate.field.queryset %}
                        <option value="{{ choise.id }}"
                                {% if certificate.value|slugify == choise.id|slugify %}
                                selected{% endif %}
                                data-subtext="{{ choise }}">{{ choise.subject.cname }}</option>
                    {% endfor %}
                </select>
                {% include "connections/forms/../widgets/errormsg.html" with field=certificate %}
            </div>
            <div class="col-sm-1 col-xs-2">
                {% include "connections/widgets/QuestionPopover.html" with title="CA certificate help" content="Select a certificate that authenticates the opposite server. Choose either the server certificate directly or the CA certificate. If no ca certificate is available 'Choose automatically' will be disabled." %}
            </div>
            <div class="col-sm-11 col-xs-10">
                <div class="pull-right cert_upload">
                    <a data-toggle="modal" data-target="#AddCaCertificateModal">Upload new certificate</a>
                </div>
            </div>
        </div>
        <div class="row is_server_identity">
            <label class="control-label col-sm-3 col-xs-12">{{ identity.label }}</label>
            <div class="col-sm-8 col-xs-10">
                <span>
                <input type="checkbox" class="is_server_identity" name="{{ is_server_identity.name }}"
                       id="{{ is_server_identity.name }}"
                       placeholder="Hostname or IP" {% if is_server_identity.value %}checked{% endif %}>
                Use server value
                </span>
            </div>
        </div>
        <div class="row identity_picker">
            <label class="control-label col-sm-3"></label>
            <div class="col-sm-8 col-xs-10">
                <input type="text" class="form-control" name="{{ identity.name }}" id="{{ identity.name }}"
                       placeholder="Custom server identity" {% if identity.value %}value="{{ identity.value }}"
                       {% else %}value=""{% endif %}/>
                {% include "connections/forms/../widgets/errormsg.html" with field=identity %}
            </div>
            <div class="col-sm-1 col-xs-2" id="{{ identity.name }}_questionpopover">
                {% include "connections/widgets/QuestionPopover.html" with title="CA identity help" content="Enter the server identity either as a domain name like 'vpn.myenterprise.com' or as a IP like '213.56.143.8'. The CA identity is the same like the server in the most cases. This field will be enabled as soon as the certificate is selected." %}
            </div>
        </div>


        <!-- Modal -->
        <div class="modal fade" id="AddCaCertificateModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Upload certificate</h4>
                    </div>
                    <div class="modal-body text-center">
                        <p>Upload a certificate. A private key is not needed.</p>
                        <iframe src="{% url "certificates:add_form" %}" frameborder="0"
                                style="width: 100%; height: 600px;"></iframe>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Finish</button>
                    </div>
                </div>
            </div>
        </div>

        <script>
            var caPicker = new CaPicker("ca_picker_{{ certificate.name }}", "{% url "connections:capicker" %}", "{{ csrf_token }}");
            var caAuto = new CaAuto("ca_picker_{{ certificate.name }}");

        </script>
    </div>
{% endwith %}

strongMan/apps/connections/templates/connections/forms/CertificatePicker.html
<div id="certificateident_picker_{{ certificate.name }}">
    <div class="row certificate_picker">
        <label class="control-label col-sm-3 col-xs-12">{{ certificate.label }}</label>
        <div class="col-sm-8 col-xs-10">
            <select class="selectpicker certificateselect" data-live-search="true"
                    name="{{ certificate.name }}"
                    id="id_{{ certificate.name }}" data-show-subtext="True">
                {% if certificate.value == None or certificate.value == '-1' %}
                    <option value="-1" selected>Nothing selected</option>
                {% endif %}
                {% for choise in certificate.field.queryset %}
                    <option value="{{ choise.id }}"
                            {% if certificate.value|slugify == choise.id|slugify %}
                            selected{% endif %}
                            data-subtext="{{ choise }}">{{ choise.subject.cname }}</option>
                {% endfor %}
            </select>
            {% include "connections/forms/../widgets/errormsg.html" with field=certificate %}
        </div>
        <div class="col-sm-1 col-xs-2">
            {% include "connections/widgets/QuestionPopover.html" with title="User certificate help" content="Select a certificate which authenticates yourself. Only certificate with a private key are shown." %}
        </div>
        <div class="col-sm-11 col-xs-10">
            <div class="pull-right cert_upload">
                <a data-toggle="modal" data-target="#AddCertificateModal">Upload new certificate</a>
            </div>
        </div>
    </div>
    <div class="row identity_picker">
        <label class="control-label col-sm-3 col-xs-12">{{ identity.label }}</label>
        <div class="col-sm-8 col-xs-10">
            <select class="selectpicker identityselect" data-live-search="true" name="{{ identity.name }}"
                    id="id_{{ identity.name }}" data-show-subtext="True"
                    {% if identity.field.choices|length == 0 %}disabled="True"{% endif %}>
                {% for value, identity_choice in identity.field.choices %}
                    <option value="{{ value }}"
                            {% if identity.value|slugify == value|slugify %}selected={% endif %}
                                    data-subtext="{{ identity_choice.type }}"
                            {% if not identity.value and identity_choice.type == 'distinguishedName' %}
                            selected
                            {% endif %}>{{ identity_choice }}
                    </option>
                {% endfor %}

            </select>
            {% include "connections/forms/../widgets/errormsg.html" with field=identity %}
        </div>
        <div class="col-sm-1 col-xs-2">
            {% include "connections/widgets/QuestionPopover.html" with title="Identity help" content="Select one of the available identities. Use the distinguished name in doubt. This field will be enabled as soon as the certificate is selected." %}
        </div>

    </div>


    <!-- Modal -->
    <div class="modal fade" id="AddCertificateModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Upload certificate</h4>
                </div>
                <div class="modal-body text-center">
                    <p>Upload a certificate first followed by the associated private key.</p>
                    <iframe src="{% url "certificates:add_form" %}" frameborder="0"
                            style="width: 100%; height: 600px;"></iframe>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Finish</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        var picker = new CertificatePicker("certificateident_picker_{{ certificate.name }}", "{% url "connections:certificatepicker" %}", "{{ csrf_token }}");
    </script>
</div>

strongMan/apps/connections/templates/connections/forms/ChooseType.html
{% load connections_extras %}
<div id="TypeChoose-form">
    <p>The authentication method should be given you by your network administrator.</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="current_form" value="{{ form|classname }}"/>
        <label class="control-label col-sm-2 col-xs-12" for="label_form_name">Method</label>
        <div class="controls col-sm-9 col-xs-10">
            <select class="selectpicker" name="form_name" id="select_form_name" onchange="this.form.submit()">
                <option>Choose your authentication method</option>
                {% for key, value in form.fields.form_name.choices %}
                    <option value={{ key }}>{{ value }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-sm-1 col-xs-2">
            {% include "connections/widgets/QuestionPopover.html" with title="Method help" content="The authentication method has to fit to your server configuration." %}
        </div>
    </form>
</div>

strongMan/apps/connections/templates/connections/forms/Ike2Certificate.html
{% extends "connections/forms/ConnectionForm.html" %}
{% load connections_extras %}
{% block form_content %}
    <div class="row">
        <div class="col-xs-12">
            <p>Choose your certificate which authenticates you. Only certificates with private key's are shown.</p>
        </div>
    </div>
    {% include "connections/forms/CertificatePicker.html" with certificate=form.certificate identity=form.identity %}
    <hr>
    <div class="row">
        <div class="col-xs-12">
            <p>Choose the certification authority (CA) certificate which authenticates the server.</p>
        </div>
    </div>
    {% include "connections/forms/CaPicker.html" with form=form %}
    <hr>

{% endblock form_content %}

strongMan/apps/connections/templates/connections/forms/Ike2EAP.html
{% extends "connections/forms/ConnectionForm.html" %}
{% load connections_extras %}
{% block form_content %}
    {% include "connections/forms/UserPassword.html" with username=form.username password=form.password %}
    <hr>
    <div class="row">
        <div class="col-xs-12">
            <p>Choose the ca certificate which authenticates the server.</p>
        </div>
    </div>
    {% include "connections/forms/CaPicker.html" with form=form %}
    <hr>
{% endblock form_content %}

strongMan/apps/connections/templates/connections/forms/Ike2EapCertificate.html
{% extends "connections/forms/ConnectionForm.html" %}
{% load connections_extras %}
{% block form_content %}
    {% include "connections/forms/UserPassword.html" with username=form.username password=form.password %}
    <hr>
    <div class="row">
        <div class="col-xs-12">
            <p>Choose your certificate which authenticates you. Only certificates with private keys are shown.</p>
        </div>
    </div>
    {% include "connections/forms/CertificatePicker.html" with certificate=form.certificate identity=form.identity %}
    <hr>
    <div class="row">
        <div class="col-xs-12">
            <p>Choose the ca certificate which authenticates the server.</p>
        </div>
    </div>
    {% include "connections/forms/CaPicker.html" with form=form %}
    <hr>
{% endblock form_content %}

strongMan/apps/connections/templates/connections/forms/Ike2EapTls.html
{% extends "connections/forms/ConnectionForm.html" %}
{% load connections_extras %}
{% block form_content %}
    <div class="row">
        <div class="col-xs-12">
            <p>Choose your certificate which authenticates you. Only certificates with private key's are shown.</p>
        </div>
    </div>
    {% include "connections/forms/CertificatePicker.html" with certificate=form.certificate identity=form.identity %}
    <hr>
    <div class="row">
        <div class="col-xs-12">
            <p>Choose the ca certificate which authenticates the server.</p>
        </div>
    </div>
    {% include "connections/forms/CaPicker.html" with form=form %}
    <hr>
{% endblock form_content %}