strongMan/apps/pools/urls.py
from django.urls import re_path

from . import views

app_name = 'pools'
urlpatterns = [
    re_path(r'^$', views.overview, name='index'),
    re_path(r'add$', views.add, name='add'),
    re_path(r'add_form$', views.add_form, name='add_form'),
    re_path(r'refreshdetails$', views.refreshdetails, name='refreshdetails'),
    re_path(r'^(?P<poolname>[0-9a-zA-Z_\-]+)$', views.edit, name='edit'),
]

strongMan/urls.py
from django.conf import settings
from django.urls import re_path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .apps import views
from .apps.certificates import urls as certificates_url
from .apps.eap_secrets import urls as eap_secrets_url
from .apps.connections import urls as connections_urls
from .apps.server_connections import urls as server_connections_urls
from .apps.pools import urls as pools
from .apps.views import index

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^connections/', include(connections_urls)),
    re_path(r'^server_connections/', include(server_connections_urls)),
    re_path(r'^pools/', include(pools)),
    re_path(r'^certificates/', include(certificates_url)),
    re_path(r'^eap_secrets/', include(eap_secrets_url)),
    re_path(r'^login/?$', views.login, name='login'),
    re_path(r'^logout/?$', views.logout, name='logout'),
    re_path(r'change_pw$', views.pw_change, name='pw_change'),
    re_path(r'^about/?$', views.about, name='about'),
]

handler400 = 'strongMan.apps.views.bad_request'
handler403 = 'strongMan.apps.views.permission_denied'
handler404 = 'strongMan.apps.views.page_not_found'
handler500 = 'strongMan.apps.views.server_error'

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

strongMan/apps/pools/models/pools.py
from django.db import models

ATTRIBUTE_CHOICES = (
    (None, 'None'),
    ('dns', 'dns'),
    ('nbns', 'nbns'),
    ('dhcp', 'dhcp'),
    ('netmask', 'netmask'),
    ('server', 'server'),
    ('subnet', 'subnet'),
    ('split_include', 'split_include'),
    ('split_exclude', 'split_exclude'),
)


class Pool(models.Model):
    poolname = models.TextField(unique=True)
    addresses = models.TextField()
    attribute = models.CharField(max_length=56, choices=ATTRIBUTE_CHOICES, null=True)
    attributevalues = models.TextField(null=True)

    @classmethod
    def create(cls, poolname, addresses, attribute, attributevalues):
        pool = cls(poolname=poolname, addresses=addresses, attribute=attribute,
                   attributevalues=attributevalues)
        return pool

    def dict(self):
        if self.poolname == 'radius' or self.poolname == 'dhcp':
            pools = None
        elif self.attribute is None:
            pools = {self.poolname: {'addrs': self.addresses}}
        else:
            pools = {self.poolname: {
                'addrs': self.addresses,
                self.attribute: self.attributevalues.split(',')}
            }
        return pools

    def __str__(self):
        return str(self.poolname)

    def __repr__(self):
        return str(self.poolname)

strongMan/apps/pools/forms.py
from django import forms
from strongMan.apps.pools.models.pools import ATTRIBUTE_CHOICES


class AddOrEditForm(forms.Form):
    poolname = forms.RegexField(max_length=50, initial="", regex=r'^[0-9a-zA-Z_\-]+$')
    addresses = forms.CharField(initial="")
    attribute = forms.ChoiceField(widget=forms.Select(), choices=ATTRIBUTE_CHOICES)
    attributevalues = forms.CharField(initial="", required=False)

    def fill(self, pool):
        self.initial['poolname'] = pool.poolname
        self.initial['addresses'] = pool.addresses
        self.initial['attribute'] = pool.attribute
        if pool.attribute is None:
            self.initial['attributevalues'] = ""
        else:
            self.initial['attributevalues'] = pool.attributevalues

    def update_pool(self, pool):
        pool.poolname = self.cleaned_data['poolname']
        pool.addresses = self.cleaned_data['addresses']
        if self.cleaned_data['attribute'] == 'None':
            pool.attribute = None
            pool.attributevalues = None
        else:
            pool.attribute = self.cleaned_data['attribute']
            pool.attributevalues = self.cleaned_data['attributevalues']

    def is_valid(self):
        valid = super(AddOrEditForm, self).is_valid()
        return valid

    @property
    def my_poolname(self):
        return self.cleaned_data["poolname"]

    @my_poolname.setter
    def my_poolname(self, value):
        self.initial['poolname'] = value

    @property
    def my_addresses(self):
        return self.cleaned_data["addresses"]

    @my_addresses.setter
    def my_addresses(self, value):
        self.initial['addresses'] = value

    @property
    def my_attribute(self):
        return self.cleaned_data["attribute"]

    @my_attribute.setter
    def my_attribute(self, value):
        self.initial['attribute'] = value

    @property
    def my_attributevalues(self):
        return self.data["attributevalues"]

    @my_attributevalues.setter
    def my_attributevalues(self, value):
        self.initial['attributevalues'] = value

strongMan/apps/pools/views/AddHandler.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from ..models import Pool
from ..forms import AddOrEditForm
from django.db import IntegrityError
from strongMan.helper_apps.vici.wrapper.exception import ViciException
from strongMan.helper_apps.vici.wrapper.wrapper import ViciWrapper
from django.shortcuts import render


class AddHandler(object):
    def __init__(self, is_add_form=False):
        self.form = None
        self.request = None
        self.is_add_form = is_add_form

    @classmethod
    def by_request(cls, request, is_add_form=False):
        handler = cls(is_add_form)
        handler.request = request
        return handler

    def _render(self, form):
        if self.is_add_form:
            return render(self.request, 'pools/add_form.html', {"form": form})
        else:
            return render(self.request, 'pools/add.html', {"form": form})

    def handle(self):
        self.form = AddOrEditForm(self.request.POST)
        if not self.form.is_valid():
            return self._render(self.form)

        if self.form.my_poolname.lower() == 'dhcp' or self.form.my_poolname.lower() == 'radius':
            messages.add_message(self.request, messages.ERROR,
                                 'Poolname "' + self.form.my_poolname + '" not allowed in pool creation. To '
                                 'use this name, please reference it directly from the connection wizard.')
            return self._render(self.form)

        else:
            if self.form.my_attribute == 'None':
                if self.form.my_attributevalues != "":
                    messages.add_message(self.request, messages.ERROR,
                                         'Can\'t add pool: Attribute values unclear for Attribute "None"')
                    return self._render(self.form)
                pool = Pool(poolname=self.form.my_poolname, addresses=self.form.my_addresses)
            else:
                if self.form.my_attributevalues == "":
                    messages.add_message(self.request, messages.ERROR,
                                         'Can\'t add pool: Attribute values mandatory if attribute is set.')
                    return self._render(self.form)
                attr = self.form.my_attribute
                pool = Pool(poolname=self.form.my_poolname, addresses=self.form.my_addresses,
                            attribute=attr,
                            attributevalues=self.form.my_attributevalues)
        try:
            pool.clean()
            vici = ViciWrapper()
            vici.load_pool(pool.dict())
            pool.save()

        except ViciException as e:
            messages.add_message(self.request, messages.ERROR, str(e))
            pool.delete()
            return self._render(self.form)
        except IntegrityError:
            messages.add_message(self.request, messages.ERROR,
                                 'Poolname already in use.')
            return self._render(self.form)

        messages.add_message(self.request, messages.SUCCESS, 'Successfully added pool')
        if self.is_add_form:
            return render(self.request, 'pools/add_form.html', {"form": AddOrEditForm()})
        else:
            return redirect(reverse("pools:index"))

strongMan/apps/pools/views/EditHandler.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.shortcuts import render
from ..forms import AddOrEditForm
from strongMan.apps.pools.models import Pool
from strongMan.helper_apps.vici.wrapper.exception import ViciException
from strongMan.helper_apps.vici.wrapper.wrapper import ViciWrapper
from django.db import transaction
from django.db.models import ProtectedError


class EditHandler(object):
    def __init__(self, request, poolname):
        self.form = None
        self.request = request
        self.poolname = poolname
        self.pool = Pool.objects.get(poolname=self.poolname)

    def handle(self):
        if self.request.method == "GET":
            return self.load_edit_form()

        elif self.request.method == "POST":
            self.form = AddOrEditForm(self.parameter_dict)
            vici = ViciWrapper()
            if "remove_pool" in self.request.POST:
                return self.delete_pool(vici)

            return self.update_pool(vici)

    def load_edit_form(self):
        form = AddOrEditForm()
        form.fill(self.pool)
        return render(self.request, 'pools/edit.html', {"form": form})

    def update_pool(self, vici):
        if not self.form.is_valid():
            return render(self.request, 'pools/edit.html', {"form": self.form})
        else:
            if self.form.my_attribute == 'None':
                if self.form.my_attributevalues != "":
                    messages.add_message(self.request, messages.ERROR,
                                         'Won\'t update: Attribute values unclear for Attribute "None"')
                    return render(self.request, 'pools/edit.html', {"form": self.form})
            else:
                if self.form.my_attributevalues == "":
                    messages.add_message(self.request, messages.ERROR,
                                         'Won\'t update: Attribute values mandatory if attribute is set.')
                    return render(self.request, 'pools/edit.html', {"form": self.form})
            msg = 'Successfully updated pool'

            try:
                self.form.update_pool(self.pool)
                self.pool.clean()
                vici.load_pool(self.pool.dict())
                self.pool.save()
                messages.add_message(self.request, messages.SUCCESS, msg)
            except ViciException as e:
                messages.add_message(self.request, messages.ERROR, str(e))
                return render(self.request, 'pools/edit.html', {"form": self.form})

            return redirect(reverse("pools:index"))

    def delete_pool(self, vici):
        vici_poolname = {"name": self.poolname}
        try:
            with transaction.atomic():
                self.pool.delete()
                if self.poolname in vici.get_pools(vici_poolname):
                    vici.unload_pool(vici_poolname)
                messages.add_message(
                    self.request, messages.SUCCESS, "Pool deletion successful."
                )
        except ViciException as e:
            messages.add_message(
                self.request, messages.ERROR, "Unload pool failed: " + str(e)
            )
        except ProtectedError as e:
            names = sorted(obj.profile for obj in e.protected_objects)
            messages.add_message(
                self.request,
                messages.ERROR,
                f"Pool not deleted! In use by {len(names)} connection(s): {', '.join(names)}",
            )
        except Exception as e:
            messages.add_message(self.request, messages.ERROR, str(e))
        return redirect(reverse("pools:index"))

    @property
    def parameter_dict(self):
        parameters = self.request.POST.copy()
        parameters['poolname'] = self.poolname
        return parameters

strongMan/apps/pools/views/OverviewHandler.py
from django.contrib import messages
from django.shortcuts import render
from django_tables2 import RequestConfig
from strongMan.apps.pools.models import Pool
from strongMan.helper_apps.vici.wrapper.exception import ViciException
from .. import tables
from strongMan.helper_apps.vici.wrapper.wrapper import ViciWrapper


class OverviewHandler(object):
    def __init__(self, request):
        self.request = request
        self.ENTRIES_PER_PAGE = 50

    def handle(self):
        try:
            return self._render()
        except ViciException as e:
            messages.warning(self.request, str(e))

    def _render(self):
        dhcpdbvalue = Pool.objects.all().filter(poolname__contains='dhcp')
        if not dhcpdbvalue:
            dhcppool = Pool(poolname='dhcp')
            dhcppool.clean()
            dhcppool.save()

        radiusdbvalue = Pool.objects.all().filter(poolname__contains='radius')
        if not radiusdbvalue:
            radiuspool = Pool(poolname='radius')
            radiuspool.clean()
            radiuspool.save()

        queryset = Pool.objects.exclude(poolname__contains='dhcp').exclude(poolname__contains='radius')
        pools = ViciWrapper().get_pools({'leases': "yes"})
        table = tables.PoolsTable(queryset, request=self.request, pools=pools)

        RequestConfig(self.request, paginate={"per_page": self.ENTRIES_PER_PAGE}).configure(table)
        if len(queryset) == 0:
            table = None
        return render(self.request, 'pools/overview.html', {'table': table})

strongMan/apps/pools/views/PoolRefreshHandler.py
from django.contrib import messages
from django.shortcuts import render
from strongMan.helper_apps.vici.wrapper.exception import ViciException
from strongMan.helper_apps.vici.wrapper.wrapper import ViciWrapper


class PoolRefreshHandler(object):
    def __init__(self, request):
        self.request = request
        self.ENTRIES_PER_PAGE = 50

    def handle(self):
        try:
            return self._render()
        except ViciException as e:
            messages.warning(self.request, str(e))

    def _render(self):
        pooldetails = ViciWrapper().get_pools({'leases': "yes"})
        table = {"pools": pooldetails}
        return render(self.request, 'pools/widgets/detailPoolTable.html',
                      {'table': table, 'is_refresh': True})

strongMan/apps/pools/templates/pools/widgets/QuestionPopover.html
<a tabindex="99" class="question glyphicon glyphicon-question-sign" role="button" data-toggle="popover"
   title="{{ title }}" data-placement="left"
   data-content="{{ content }}"></a>

strongMan/apps/pools/templates/pools/widgets/addPool.html
<div class="container" id="pools-add">
    <div class="panel panel-default col-md-8 col-md-offset-2 col-xs-12" id="upload-panel">
        <div class="panel-body" id="upload-area">
            <form method="post">
                {% csrf_token %}

                <div class="row">
                    <label class="control-label col-sm-3 col-xs-12">Pool name*</label>
                    <div class="controls col-sm-8 col-xs-10">
                        <input type="text" class="form-control" name="poolname" value="{{ form.poolname.value }}"
                               placeholder="Pool name"/>
                        {% include "pools/widgets/errormsg.html" with field=form.poolname %}
                    </div>
                    <div class="col-sm-1 col-xs-2">
                        {% include "pools/widgets/QuestionPopover.html" with title="Pool name help" content="Choose a name for your pool. 'dhcp' and 'radius' are reserved keywords. These can be used from the server connections wizard directly. There's no need to create such a pool." %}
                    </div>
                </div>

                <div class="row">
                    <label class="control-label col-sm-3 col-xs-12">Addresses*</label>
                    <div class="controls col-sm-8 col-xs-10">
                        <input type="text" class="form-control" name="addresses" value="{{ form.addresses.value }}"
                               placeholder="Address list"/>
                        {% include "pools/widgets/errormsg.html" with field=form.addresses %}
                    </div>
                    <div class="col-sm-1 col-xs-2">
                        {% include "pools/widgets/QuestionPopover.html" with title="Addresses help" content="Enter the (IPv4 or IPv6) addresses or address ranges of the pool comma separated. Examples: 192.168.1.0/24, 192.168.2.10-192.168.2.15" %}
                    </div>
                </div>

                <div class="row">
                    <label class="control-label col-sm-3 col-xs-12">Attribute</label>
                    <div class="controls col-sm-8 col-xs-10">
                        <select class="selectpicker" name="attribute">
                            {% for choice in form.attribute.field.choices %}
                                <option value="{{choice.0}}"
                                {% if form.attribute.value == choice.0 %}
                                     selected="selected"
                                {% endif %}>
                                    {{choice.1}}
                                </option>
                            {% endfor %}
                        </select>
                        {% include "pools/widgets/errormsg.html" with field=form.attribute %}
                    </div>
                    <div class="col-sm-1 col-xs-2">
                        {% include "pools/widgets/QuestionPopover.html" with title="Attributes" content="Select an additional attribute. (optional)" %}
                    </div>
                </div>

                <div class="row">
                    <label class="control-label col-sm-3 col-xs-12">Attribute values</label>
                    <div class="controls col-sm-8 col-xs-10">
                        <input type="text" class="form-control" name="attributevalues" value="{{ form.attributevalues.value }}"
                               placeholder="Attribute values"/>
                        {% include "pools/widgets/errormsg.html" with field=form.attributevalues %}
                    </div>
                    <div class="col-sm-1 col-xs-2">
                        {% include "pools/widgets/QuestionPopover.html" with title="Attribute help" content="Enter the address of the additional attribute. This field is required if attribute is set." %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-11 col-xs-12">
                        <button type="submit" class="btn btn-default pull-right">
                            <span class="glyphicon glyphicon-floppy-disk"></span> Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script>
        $(function () {
            $(document).popover({
                selector: '[data-toggle=popover]',
                trigger: 'focus',
                container: 'body'
            });
          });
    </script>
</div>

strongMan/apps/pools/templates/pools/widgets/address_column.html
<span>{{ record.Addresses }}</span>

strongMan/apps/pools/templates/pools/widgets/detailPoolTable.html
{% for key, val in table.pools.items %}
    {% if is_refresh == True or record.poolname == key %}
        <table>
            <tbody id="{{ key }}">
                {% if is_refresh != True %}
                <tr><td><b>Attribute:</b></td> <td> {{ record.attribute }}<br /></td></tr>
                <tr><td><b>Attributevalue(s):</b> </td> <td> {{ record.attributevalues }}<br /></td></tr>
                {% endif %}
                <tr><td><b># of addresses in pool:</b> </td> <td> {{ val.size }}<br /></td></tr>
                <tr><td><b>Virtual IP pool base address:</b> </td> <td> {{ val.base }}<br /></td></tr>
                <tr><td><b># of online:</b> </td> <td> {{ val.online }}<br /></td></tr>
                <tr><td><b># of offline:</b> </td> <td> {{ val.offline }}<br /></td></tr>
                {% if 'leases' in val %}
                    <tr><td><b>Leases in {{ key }}:</b> </td>
                    <td>
                        {% if val.leases|length == 0 %}
                            No leases.
                        {% else %}
                            {%  for k, v in  val.leases.items %}
                                <tr><td>{{ v.identity }}</td><td>{{ v.address }}, {{ v.status }} </td></tr>
                            {% endfor %}
                        {% endif %}
                    </td></tr>
                {% endif %}
            </tbody>
        </table>
    {% endif %}
{% endfor %}

strongMan/apps/pools/templates/pools/widgets/detail_collapse_column.html
<div id="grow" class="collapsepool">
    <a for="collapse{{ record.poolname }}" role="button" data-toggle="collapse"
       href="#collapse{{ record.poolname }}" aria-expanded="false" aria-controls="collapse{{ record.poolname }}"
         class="accordion-toggle collapsed"></a>

</div>

strongMan/apps/pools/templates/pools/widgets/errormsg.html
{% if field.errors %}
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign"
              aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        {% for error in field.errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}

strongMan/apps/pools/templates/pools/widgets/name_column.html
<a href="{% url "pools:edit" record.poolname %}">{{ record.poolname }}</a>

strongMan/apps/pools/templates/pools/widgets/remove_column.html
<form action="{% url "pools:edit" poolname %}" method="POST" class="inline-form"
      onsubmit="return removeBtnClicked(this)" id="{{ poolname }}">
    {% csrf_token %}
    <span title="Remove">
        <button type="submit" class="btn btn-default remove-btn btn-sm"
                id="removebtn-{{ poolname }}" name="remove_pool">
            <span class="glyphicon glyphicon-remove"></span><span class="removebtn-text"></span>
        </button>
    </span>
</form>
<script>
    function removeBtnClicked(form) {
        btn = $("#removebtn-" + form.id);
        if (btn.hasClass('btn-default')) {
            btn.removeClass('btn-default').addClass('btn-danger');
            btn.children('.removebtn-text').text('Remove');
            return false;
        } else {
            return true;
        }
    }
</script>

strongMan/apps/pools/templates/pools/widgets/table.html
{% load django_tables2 %}
{% load i18n %}
<div class="old table-container">
    {% block table %}
        <table{% if table.attrs %} {{ table.attrs.as_html }}{% endif %} id="poolTable">
            {% block table.thead %}
                {% if table.show_header %}
                    <thead>
                    <tr>
                        {% for column in table.columns %}
                            {% if column.orderable %}
                                <th {{ column.attrs.th.as_html }}><a
                                        href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                                </th>
                            {% else %}
                                <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    </thead>
                {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody>
                {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
                    {% block table.tbody.row %}
                        <tr class="{% cycle 'even' 'odd' %} ">
                            {% for column, cell in row.items %}
                                <td {{ column.attrs.td.as_html }}>
                                    {% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}
                                        {{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}
                                </td>
                            {% endfor %}
                        </tr>

                        <tr id="collapse{{ row.record.poolname }}" class="collapse refreshpools" >
                            <td colspan="4">
                                {% include "pools/widgets/detailPoolTable.html" with record=row.record %}
                            </td>
                        </tr>

                    {% endblock table.tbody.row %}


                    {% empty %}
                    {% if table.empty_text %}
                        {% block table.tbody.empty_text %}
                            <tr>
                                <td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td>
                            </tr>
                        {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
                <tfoot></tfoot>
            {% endblock table.tfoot %}

        </table>
    {% endblock table %}

    {% if table.page %}
        {% with table.page.paginator.count as total %}
            {% with table.page.object_list|length as count %}
                {% block pagination %}
                    {% if table.page.has_previous %}
                        <div class="text-center">
                            {% block pagination.previous %}
                                <a class="btn btn-default" name="next"
                                   href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}">
                                    <span class="glyphicon glyphicon-chevron-left"></span> Previous
                                </a>
                            {% endblock pagination.previous %}
                        </div>
                    {% endif %}

                    {% if table.page.has_previous or table.page.has_next %}
                        {% block pagination.current %}
                            <span class="current">
                                    {% blocktrans with table.page.number as current and table.paginator.num_pages as total %}
                                        Page {{ current }} of {{ total }}
                                    {% endblocktrans %}
                                </span>
                        {% endblock pagination.current %}
                    {% endif %}

                    {% if table.page.has_next %}
                        {% block pagination.next %}
                            <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}"
                               class="btn btn-default" name="next">
                                Next <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        {% endblock pagination.next %}
                    {% endif %}
                    {% block pagination.cardinality %}
                        <div class="cardinality">
                            {% if total != count %}{% blocktrans %}{{ count }} of {{ total }}
                            {% endblocktrans %}{% else %}{{ total }}{% endif %}
                            {% if total == 1 %}{{ table.data.verbose_name }}{% else %}
                                {{ table.data.verbose_name_plural }}{% endif %}
                        </div>
                    {% endblock pagination.cardinality %}
                {% endblock pagination %}
            {% endwith %}
        {% endwith %}
    {% endif %}
</div>
<script>
    var intervalID = setInterval(function() {
        $.ajax({
            type: 'POST',
            url: "{% url "pools:refreshdetails" %}",
            data: {
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success: function (data) {
                //Replace bootstrap selects with new rendered selects
                $('.refreshpools').each(function () {
                    var table = $(this).find('tbody');
                    var poolname = "#"+table.attr("id");
                    var attribute = table.find('tr').first();
                    var attributevalues = attribute.next();
                    var poolDetails = $('<div />').html(data).find(poolname).html();
                    table.html(attribute.add(attributevalues).add(poolDetails));
                })
            },
            error: function (data) {
               throw data;
            }
        });
    }, 10000);
</script>