strongMan/apps/eap_secrets/urls.py
from django.urls import re_path

from . import views

app_name = 'eap_secrets'
urlpatterns = [
    re_path(r'add$', views.add, name='add'),
    re_path(r'^(?P<secret_name>[0-9a-zA-Z_\-]+)$', views.edit, name='edit'),
    re_path(r'$', views.overview, name='overview'),
]

strongMan/urls.py
from django.conf import settings
from django.urls import re_path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .apps import views
from .apps.certificates import urls as certificates_url
from .apps.eap_secrets import urls as eap_secrets_url
from .apps.connections import urls as connections_urls
from .apps.server_connections import urls as server_connections_urls
from .apps.pools import urls as pools
from .apps.views import index

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^connections/', include(connections_urls)),
    re_path(r'^server_connections/', include(server_connections_urls)),
    re_path(r'^pools/', include(pools)),
    re_path(r'^certificates/', include(certificates_url)),
    re_path(r'^eap_secrets/', include(eap_secrets_url)),
    re_path(r'^login/?$', views.login, name='login'),
    re_path(r'^logout/?$', views.logout, name='logout'),
    re_path(r'change_pw$', views.pw_change, name='pw_change'),
    re_path(r'^about/?$', views.about, name='about'),
]

handler400 = 'strongMan.apps.views.bad_request'
handler403 = 'strongMan.apps.views.permission_denied'
handler404 = 'strongMan.apps.views.page_not_found'
handler500 = 'strongMan.apps.views.server_error'

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

strongMan/apps/eap_secrets/models/secrets.py
from collections import OrderedDict

from django.db import models

from strongMan.helper_apps.encryption import fields


class Secret(models.Model):
    username = models.TextField(unique=True)
    type = models.TextField()
    password = fields.EncryptedCharField(max_length=50)
    salt = models.TextField()

    def dict(self):
        password = self.password[32:]
        secrets = OrderedDict(type=self.type, data=password, owners=[self.username])
        return secrets

    def __str__(self):
        return str(self.username)

strongMan/apps/eap_secrets/forms.py
from base64 import b64encode
from os import urandom
from django import forms


class EapSecretSearchForm(forms.Form):
    search_text = forms.CharField(max_length=200, required=False)


class AddOrEditForm(forms.Form):
    username = forms.RegexField(max_length=50, initial="", regex=r'^[0-9a-zA-Z_\-]+$')
    password = forms.CharField(max_length=50, widget=forms.PasswordInput, initial="")

    def __init__(self, *args, **kwargs):
        self.salt = b64encode(urandom(24)).decode('utf-8')
        super(AddOrEditForm, self).__init__(*args, **kwargs)

    def is_valid(self):
        valid = super(AddOrEditForm, self).is_valid()
        return valid

    @property
    def my_salt(self):
        return self.salt

    @property
    def my_salted_password(self):
        password = self.my_salt + self.cleaned_data["password"]
        return password

    @my_salted_password.setter
    def my_salted_password(self, value):
        password = value[32:]
        self.initial['password'] = password

    @property
    def my_username(self):
        return self.cleaned_data["username"]

    @my_username.setter
    def my_username(self, value):
        self.initial['username'] = value

    @property
    def my_password(self):
        password = self.cleaned_data["password"]
        if password == "":
            return None
        return password

    @my_password.setter
    def my_password(self, value):
        self.initial['password'] = value

strongMan/apps/eap_secrets/views/AddHandler.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.shortcuts import render
from django.db import IntegrityError

from ..forms import AddOrEditForm
from ..models import Secret
from strongMan.helper_apps.vici.wrapper.wrapper import ViciWrapper


class AddHandler(object):
    def __init__(self):
        self.form = None
        self.request = None

    @classmethod
    def by_request(cls, request):
        handler = cls()
        handler.request = request
        return handler

    def handle(self):
        if self.request.method == 'GET':
            return render(self.request, 'eap_secrets/add.html', {"form": AddOrEditForm()})

        elif self.request.method == 'POST':
            self.form = AddOrEditForm(self.request.POST)
            if not self.form.is_valid():
                return render(self.request, 'eap_secrets/add.html', {"form": self.form})
            else:
                try:
                    secret = Secret(username=self.form.my_username, type='EAP',
                                    password=self.form.my_salted_password, salt=self.form.my_salt)
                    secret.save()
                except IntegrityError:
                    messages.add_message(self.request, messages.ERROR,
                                         'An EAP Secret with this Username does already exist')
                    return render(self.request, 'eap_secrets/add.html', {"form": self.form})
                ViciWrapper().load_secret(secret.dict())
                messages.add_message(self.request, messages.SUCCESS, 'Successfully created EAP Secret')
                return redirect(reverse("eap_secrets:overview"))

strongMan/apps/eap_secrets/views/EditHandler.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.shortcuts import render
from django.db.models import ProtectedError

from ..forms import AddOrEditForm
from ..models import Secret
from strongMan.helper_apps.vici.wrapper.wrapper import ViciWrapper
from strongMan.helper_apps.vici.wrapper.exception import ViciException


class EditHandler(object):
    def __init__(self, request, secret):
        self.request = request
        self.secret = secret

    def _render_edit(self, form=AddOrEditForm()):
        return render(self.request, 'eap_secrets/edit.html', {"form": form})

    def delete_secret(self):
        try:
            store_secret = self.secret
            self.secret.delete()
            self.reload_secrets()
            messages.add_message(self.request, messages.SUCCESS, 'Successfully deleted EAP Secret')
        except ProtectedError:
            messages.add_message(self.request, messages.ERROR,
                                 'Secret not deleted! Secret is referenced by a Connection')
        except ViciException as e:
            store_secret.save()
            messages.add_message(self.request, messages.ERROR, str(e))
        return redirect(reverse("eap_secrets:overview"))

    def update_secret(self):
        form = AddOrEditForm(self.request.POST)
        if not form.is_valid():
            return self._render_edit(form)
        else:
            try:
                store_secret = self.secret
                self.secret.password = form.my_salted_password
                self.secret.salt = form.my_salt
                self.secret.save()
                self.reload_secrets()
                messages.add_message(self.request, messages.SUCCESS, 'Successfully updated EAP Secret')
            except ViciException as e:
                store_secret.save()
                messages.add_message(self.request, messages.ERROR, str(e))
                return render(self.request, 'eap_secrets/edit.html', {"form": form})
            return redirect(reverse("eap_secrets:overview"))

    def reload_secrets(self):
        vici = ViciWrapper()
        vici.clear_creds()
        for secret in Secret.objects.all():
            vici.load_secret(secret.dict())

    def handle(self):
        if self.request.method == "GET":
            form = AddOrEditForm()
            form.my_username = self.secret.username
            form.my_salted_password = self.secret.password
            return self._render_edit(form)
        elif self.request.method == "POST":
            if "remove_secret" in self.request.POST:
                return self.delete_secret()
            else:
                return self.update_secret()

strongMan/apps/eap_secrets/views/OverviewHandler.py
from django.contrib import messages
from django.shortcuts import render
from django_tables2 import RequestConfig

from ..forms import EapSecretSearchForm
from ..tables import EapSecretsTable
from ..models import Secret


class OverviewHandler(object):
    def __init__(self):
        self.request = None
        self.ENTRIES_PER_PAGE = 10

    @classmethod
    def by_request(cls, request):
        handler = cls()
        handler.request = request
        return handler

    def page_tag(self):
        return "all"

    def all_secrets(self):
        return Secret.objects.all()

    def _search_for(self, all_secrets, search_text):
        '''
        Searches for keywords in Secrets
        :param all_secrets: prefiltered list of eap secrets
        :param search_text: text to search for
        :return: queryset of filtered secrets
        '''
        secret_ids = []
        secrets = Secret.objects.all()
        for secret in secrets:
            if search_text.lower() in str(secret.username).lower():
                secret_ids.append(secret.pk)
        return all_secrets.filter(pk__in=secret_ids)

    def _render(self, queryset=Secret.objects.none(), search_pattern=""):
        table = EapSecretsTable(queryset, request=self.request)
        RequestConfig(self.request, paginate={"per_page": self.ENTRIES_PER_PAGE}).configure(table)
        if len(queryset) == 0:
            table = None
        return render(self.request, 'eap_secrets/overview.html',
                      {'table': table, "view": self.page_tag(), "search_pattern": search_pattern})

    def handle(self):
        try:
            all_secrets = self.all_secrets()
        except OverviewHandlerException as e:
            messages.add_message(self.request, messages.WARNING, str(e))
            return self._render()

        if self.request.method == "GET":
            return self._render(all_secrets)

        form = EapSecretSearchForm(self.request.POST)
        if not form.is_valid():
            return self._render(all_secrets)

        search_pattern = form.cleaned_data["search_text"]
        if not search_pattern == '':
            search_result = self._search_for(all_secrets, search_pattern)
        else:
            search_result = all_secrets
        return self._render(search_result, search_pattern)


class OverviewHandlerException(Exception):
    pass

strongMan/apps/eap_secrets/templates/eap_secrets/add.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}EAP Secrets{% endblock title %}
{% block small-title %}Create new Secret{% endblock small-title %}
{% block html-head %}
    <link href="{% static 'eap_secrets/eap_secrets.css' %}" rel="stylesheet">
    <link href="{% static 'pools/bootstrap-select.min.css' %}" rel="stylesheet">
    <script src="{% static "pools/bootstrap-select.min.js" %}"></script>
{% endblock html-head %}
{% block content %}
    <div class="container" id="eap_secrets-add">
        <div class="panel panel-default col-md-8 col-md-offset-2 col-xs-12" id="upload-panel">
            <div class="panel-body" id="upload-area">
                <form method="post">
                    {% csrf_token %}

                    <div class="row">
                        <label class="control-label col-sm-3 col-xs-12">Username</label>
                        <div class="controls col-sm-8 col-xs-10">
                            <input type="text" class="form-control" name="username" value="{{ form.username.value }}"
                                   placeholder="Your username"/>
                            {% include "eap_secrets/widgets/errormsg.html" with field=form.username %}
                        </div>
                        <div class="col-sm-1 col-xs-2">
                            {% include "eap_secrets/widgets/QuestionPopover.html" with title="Username help" content="Enter the username that authenticates the user. Only numbers and letters are allowed." %}
                        </div>
                    </div>

                    <div class="row">
                        <label class="control-label col-sm-3 col-xs-12">Password</label>
                        <div class="controls col-sm-8 col-xs-10">
                            <input type="password" class="form-control" name="password" value="{{ form.password.value }}"
                                   placeholder="Your password"/>
                            {% include "eap_secrets/widgets/errormsg.html" with field=form.password %}
                        </div>
                        <div class="col-sm-1 col-xs-2">
                            {% include "eap_secrets/widgets/QuestionPopover.html" with title="Password help" content="Enter the corresponding password. Use a safe and strong password." %}
                        </div>
                    </div>

                    <div class="row form-row">
                        <div class="col-md-11 col-xs-12">
                            <button type="submit" class="btn btn-default pull-right add_button">
                                <span class="glyphicon glyphicon-floppy-disk"></span> Create
                            </button>
                            <button type="button" name="password-visibility" class="btn btn-default pull-right">Show password</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <script>
            $(function () {
                $(document).popover({
                    selector: '[data-toggle=popover]',
                    trigger: 'focus',
                    container: 'body'
                });
                $("button[name='password-visibility']").click(function() {
                    if ($( "input[name='password']" ).attr('type') == 'password'){
                        $( "input[name='password']" ).attr('type', 'text');
                        $(this).html('Hide password');
                    }
                    else {
                        $( "input[name='password']" ).attr('type', 'password');
                        $(this).html('Show password');
                    }
                });
            });
        </script>
    </div>
{% endblock content %}

strongMan/apps/eap_secrets/templates/eap_secrets/edit.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}EAP Secrets{% endblock title %}
{% block small-title %}Edit a Secret{% endblock small-title %}
{% block html-head %}
    <link href="{% static 'eap_secrets/eap_secrets.css' %}" rel="stylesheet">
{% endblock html-head %}
{% block content %}
    <div class="container" id="eap_secrets-add">
        <div class="panel panel-default col-md-8 col-md-offset-2 col-xs-12" id="upload-panel">
            <div class="panel-body" id="upload-area">
                <form method="post" action="{% url "eap_secrets:edit" form.username.value %}">
                    {% csrf_token %}

                    <div class="row">
                        <label class="control-label col-sm-3 col-xs-12">Username</label>
                        <div class="controls col-sm-8 col-xs-10">
                            <input type="text" class="form-control" name="username" value="{{ form.username.value }}"
                                   placeholder="Your username" readonly/>
                            {% include "eap_secrets/widgets/errormsg.html" with field=form.username %}
                        </div>
                        <div class="col-sm-1 col-xs-2">
                            {% include "eap_secrets/widgets/QuestionPopover.html" with title="Username help" content="Enter the username that authenticates the user." %}
                        </div>
                    </div>

                    <div class="row">
                        <label class="control-label col-sm-3 col-xs-12">Password</label>
                        <div class="controls col-sm-8 col-xs-10">
                            <input type="password" class="form-control" name="password" value="{{ form.password.value }}"
                                   placeholder="Your password" />
                            {% include "eap_secrets/widgets/errormsg.html" with field=form.password %}
                        </div>
                        <div class="col-sm-1 col-xs-2">
                            {% include "eap_secrets/widgets/QuestionPopover.html" with title="Password help" content="Enter the corresponding password. Use a safe and strong password." %}
                        </div>
                    </div>

                    <div class="row form-row">
                        <div class="col-md-11 col-xs-12">
                            <button type="submit" class="btn btn-default pull-right add_button">
                                <span class="glyphicon glyphicon-floppy-disk"></span> Change
                            </button>
                            <button type="button" name="password-visibility" class="btn btn-default pull-right">Show password</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <script>
            $(function () {
                $(document).popover({
                    selector: '[data-toggle=popover]',
                    trigger: 'focus',
                    container: 'body'
                });
                $("button[name='password-visibility']").click(function() {
                    if ($( "input[name='password']" ).attr('type') == 'password'){
                        $( "input[name='password']" ).attr('type', 'text');
                        $(this).html('Hide password');
                    }
                    else {
                        $( "input[name='password']" ).attr('type', 'password');
                        $(this).html('Show password');
                    }
                });
            });
        </script>
    </div>
{% endblock content %}

strongMan/apps/eap_secrets/templates/eap_secrets/overview.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load render_table from django_tables2 %}
{% comment %}
    Input:
    :param publics: list of certificates
    :type publics: [models.Certifacte]
    :param view: indicates which filter has been applied
    :type view: "all" | "root" | "entities"
    :param search_pattern: the search pattern, that the user has typed in
    :type search_pattern: String
    :param readonly: Indicates if the view is readonly
    :type readonly: boolean
{% endcomment %}
{% block title %}EAP Secrets{% endblock title %}
{% block small-title %}Overview{% endblock small-title %}
{% block html-head %}
    <link href="{% static 'eap_secrets/eap_secrets.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}" />
{% endblock %} html-header %}
{% block content %}
    <div id="eap_secrets-overview" class="row col-xs-12 col-md-10 col-md-offset-1">
        <div class="row" id="header">
            <div class="pull-right" id="add-btn">
                <span title="Add a new key container">
                    <a href="{% url "eap_secrets:add" %}" type="button" class="btn btn-primary btn-sm"
                       aria-label="Left Align">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add
                    </a>
                </span>
            </div>
        </div>
        <div class="row" id="search">
            <form action="" method="POST" >
                {% csrf_token %}
                <input type="hidden" name="page" value="1">
                <div class="col-xs-12">
                    <div class="input-group">
                        <input class="form-control" type="text" name="search_text" value="{{ search_pattern }}"
                               placeholder="Filter your EAP Secrets by Name">
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default" type="button" name="search" {% if not table %}disabled="True"{% endif %}><span
                                    class="glyphicon glyphicon-search"></span> Search
                            </button>
                            <a href="" class="btn btn-default" {% if search_pattern == "" %}disabled="True"{% endif %}
                               name="clear">
                                <span class="glyphicon glyphicon-remove"></span> Clear
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    {% if table %}
        <div class="col-xs-12">
        {% render_table table 'eap_secrets/widgets/table.html' %}
        </div>
    {% else %}
        <h3 id="no_certs_to_show">No EAP Secrets to show</h3>
        <p>Feel free to add a EAP Secret with the blue Add button on the right side.</p>
    {% endif %}
    </div>
{% endblock content %}